### ISSUE TITLE
REDACT password when test user is created

### ISSUE THREAD

**Issue by shashwathi** [cloudfoundry-incubator/cf-test-helpers#31]
Hi, 

Currently when test user is created by `admin`, username and password is logged in [test output](https://github.com/cloudfoundry-incubator/cf-test-helpers/blob/master/workflowhelpers/internal/user.go#L72). This is not issue if user is deleted after test runs but if the tests are using [`test_password`](https://github.com/cloudfoundry/cf-acceptance-tests#optional-parameters) because operators have password policy set on their CF deployment, it would be easy to discover a password that meets the policy criteria. 

Regards
Shash

**Comment by dsabeti** [comment]
Hey @shashwathi, thanks for finding this. I managed to get the password to leak. I'll use this issue as a story to redact the password.

**Comment by rosenhouse** [comment]
@dsabeti is this done?

**Comment by dsabeti** [comment]
@rosenhouse, yes it is. It looks like I forgot to close the issue after accepting the story. Thanks for following up!
