### ISSUE TITLE
Making CF commands more flake-resistent

### ISSUE THREAD

**Issue by kirederik** [cloudfoundry-incubator/cf-test-helpers#39]
We use the cf-test-helpers in our tests and, sometimes, due to environment flakes, commands like `cf services` and `cf apps` fail. That bite us especially as we run asynchronous commands against CF and then poll on the status.

For example, after `cf create-service` we poll `cf service` until getting a `create successfully` back. Currently, if any `cf service` fails to execute, the test will fail immediately. We also had problems with `cf service` not completing at all.

An idea we had (and implemented) was to poll `cf service` and wait for a timeout for the command to complete. If the timeout is reached, or if it exits with non-zero status code, we just retry. We fail the test after we reach a certain number of attempts.

You can see our implementation [here](https://github.com/pivotal-cf/on-demand-service-broker/blob/master/system_tests/cf_helpers/cf.go)

We thought about submitting a PR with this changes. Is this something you'd willing to merge?

Thanks!

**Comment by dsabeti** [comment]
Hey @kirederik. [We've actually removed similar functionality from this some time ago](https://github.com/cloudfoundry-incubator/cf-test-helpers/commit/4efa2a7e4b4f4eda3f32d6b56b11d560b270a1a7), but the code we removed was much more complex and difficult to reason about than your implementation. As such, I'd be open to re-evaluating retry logic in the test helpers. I'll discuss with @staylor14 (our anchor) if it makes sense.

**Comment by albertoleal** [comment]
Hi @kirederik and @dsabeti -- any updates on this issue?

**Comment by heyjcollins** [comment]
Hey @kirederik ands @albertoleal - For the time-being we're going to hold off on merging the changes in your implementation to the  current cf-test-helpers.  We'll definitely consider as part of a broader CATs refactoring we'll be doing in the near future.
